In [3]:
import numpy as np

a = np.array([2, 1])
print(a)

b = np.array([3, 2, 1])
print(b)

A = np.array([[2, 4, 1], [6, 3, 5]])
print(A)


[2 1]
[3 2 1]
[[2 4 1]
 [6 3 5]]


In [5]:
import tensorflow as tf

a = tf.constant([2, 1])
print(a)

b = tf.constant([3, 2, 1])
print(b)

A = tf.constant([[2, 4, 1], [6, 3, 5]])
print(A)

tf.Tensor([2 1], shape=(2,), dtype=int32)
tf.Tensor([3 2 1], shape=(3,), dtype=int32)
tf.Tensor(
[[2 4 1]
 [6 3 5]], shape=(2, 3), dtype=int32)


In [6]:
import numpy as np
import math

a = np.array([3, 2])
b = np.array([1, 4])

print(a + b)
print(a - b)
print(np.linalg.norm(a))
print(np.linalg.norm(b))

def norm(x):
    return math.sqrt(sum([i ** 2 for i in x]))

print("함수를 사용한 벡터의 크기 :", norm(a))
print("함수를 사용한 벡터의 크기 :", norm(b))

[4 6]
[ 2 -2]
3.605551275463989
4.123105625617661
함수를 사용한 벡터의 크기 : 3.605551275463989
함수를 사용한 벡터의 크기 : 4.123105625617661


In [9]:
import numpy as np

a = np.array([3, 2])
b = np.array([1, 4])
ans = 0
for i in range(2):
    ans += a[i] * b[i]

print(ans)

c = np.array([2, 1])
d = np.array([-1, 2])

print(c.dot(d))

11
11
0


In [11]:
import numpy as np

X = np.array([[1, 2, 3], [3, 4, 5]])
Y = np.array([[3, 4, 5], [4, 5, 6]])

print(X + Y)
print(X - Y)

[[ 4  6  8]
 [ 7  9 11]]
[[-2 -2 -2]
 [-1 -1 -1]]


In [13]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[3, 4], [4, 5], [5, 6]])

print(A.dot(B))

C = np.matrix([[1, 2, 3], [3, 4, 5]])
D = np.matrix([[3, 4], [4, 5], [5, 6]])

print(C * D)
print(A @ B)

[[26 32]
 [50 62]]
[[26 32]
 [50 62]]
[[26 32]
 [50 62]]


In [14]:
import numpy as np

A = np.array([[2, 5], [1, 3]])
print(np.linalg.inv(A))

[[ 3. -5.]
 [-1.  2.]]


In [15]:
import numpy as np

A = np.array([[2, 5], [1, 3]])
print(np.linalg.det(A))

B = np.array([[1, 4, 2], [3, -1, -2], [-3, 1, 3]])
print(np.linalg.det(B))

1.0
-13.0


In [17]:
import numpy as np

A = np.array([[2, 3], [-1, 4]])
B = np.array([7, 2])

print(np.linalg.inv(A) @ B)

[2. 1.]


In [23]:
# 연습 문제 5-1
import numpy as np

A = np.array([[3, -2], [4, 5]])
print(np.linalg.inv(A))

B = np.array([[1, -3, 4], [-2, 5, 3], [2, -1, 0]])
print(np.linalg.inv(B))

C = np.array([[-1, 5, 2, -3], [0, 3, -1, 4], [2, -3, 0, -5], [-4, 2, 3, 1]])
print(np.linalg.inv(C))

[[ 0.2173913   0.08695652]
 [-0.17391304  0.13043478]]
[[-0.06382979  0.08510638  0.61702128]
 [-0.12765957  0.17021277  0.23404255]
 [ 0.17021277  0.10638298  0.0212766 ]]
[[-0.5      2.75     2.75     1.25   ]
 [ 0.1875  -0.09375 -0.21875 -0.15625]
 [-0.6875   3.34375  3.46875  1.90625]
 [-0.3125   1.15625  1.03125  0.59375]]


In [27]:
# 연습문제 6
import numpy as np

A = np.array([[2, 5, -4], [3, -2, 6], [-1, 3, -2]])
X = np.array([9, 9, 4])
print(np.linalg.inv(A) * X, end="\n\n")

B = np.array([[-1, 3, 5, 2], [4, -6, 3, -1], [3, 3, -4, 3], [2, -1, 2, -4]])
Y = np.array([8, -32, 26, -25])
print(np.linalg.inv(B) * Y)

[[ 2.25        0.32142857 -1.57142857]
 [ 0.          1.28571429  1.71428571]
 [-1.125       1.76785714  1.35714286]]

[[ 0.27722772 -2.5029703   4.1960396  -2.97029703]
 [ 0.63366337  3.42178218  2.16237624 -3.21782178]
 [ 1.06930693 -1.42574257 -0.9009901  -0.74257426]
 [ 0.51485149 -2.81980198  1.10693069  5.1980198 ]]
