In [1]:
# 넘파이로 합성곱층의 순전파를 계산
import numpy as np

# 입력 데이터
x = np.array([[0, 1, 2, 1, 0, 0], [0, 0, 1, 2, 1, 0], [0, 0, 0, 1, 2, 1],
             [0, 0, 0, 1, 3, 2], [1, 1, 1, 3, 2, 0], [2, 2, 3, 2, 1, 0]])

# 필터
f = np.array([[0, 1, 1], [0, 1, 1], [0, 1, 1]])

result = []
for i in range(len(x) - len(f) + 1):
    row = []
    for j in range(len(x[0]) - len(f[0]) + 1):
        row.append(np.sum(x[i : i + len(f), j : j + len(f[0])] * f))
    result.append(row)
print(result)

[[4, 7, 7, 4], [1, 5, 10, 9], [2, 6, 12, 10], [7, 10, 12, 8]]


In [2]:
# 사이파이로 합성곱층의 순전파 계산
from scipy import signal

x = [[0, 1, 2, 1, 0, 0], [0, 0, 1, 2, 1, 0], [0, 0, 0, 1, 2, 1],
    [0, 0, 0, 1, 3, 2], [1, 1, 1, 3, 2, 0], [2, 2, 3, 2, 1, 0]]

f = [[0, 1, 1], [0, 1, 1], [0, 1, 1]]

print(signal.correlate(x, f, 'valid'))

[[ 4  7  7  4]
 [ 1  5 10  9]
 [ 2  6 12 10]
 [ 7 10 12  8]]


In [3]:
# 넘파이로 풀링층의 순전파를 계산
import numpy as np

# 입력 데이터
x = np.array([[0, 0, 1, 0, 0, 0], [0, 0, 2, 0, 0, 0], [0, 1, 2, 1, 0, 0],
             [0, 1, 2, 1, 0, 0], [1, 2, 2, 2, 1, 0], [1, 2, 3, 2, 1, 0]])

result = []
for i in range(0, len(x), 2):
    row = []
    for j in range(0, len(x[0]), 2):
        row.append(np.max(x[i : i+2, j : j+2]))
    result.append(row)
print(result)

[[0, 2, 0], [1, 2, 0], [2, 3, 1]]
